// Code generated by protoc-gen-go.
// source: egregor.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	egregor.proto

It has these top-level messages:
	CommandRequest
	CommandResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CommandRequest struct {
	Nick    string   `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
	Command string   `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
}

func (m *CommandRequest) Reset()                    { *m = CommandRequest{} }
func (m *CommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()               {}
func (*CommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CommandResponse struct {
	Reply []string `protobuf:"bytes,1,rep,name=reply" json:"reply,omitempty"`
}

func (m *CommandResponse) Reset()                    { *m = CommandResponse{} }
func (m *CommandResponse) String() string            { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()               {}
func (*CommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CommandRequest)(nil), "pb.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "pb.CommandResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Command service

type CommandClient interface {
	DoCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type commandClient struct {
	cc *grpc.ClientConn
}

func NewCommandClient(cc *grpc.ClientConn) CommandClient {
	return &commandClient{cc}
}

func (c *commandClient) DoCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := grpc.Invoke(ctx, "/pb.Command/DoCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Command service

type CommandServer interface {
	DoCommand(context.Context, *CommandRequest) (*CommandResponse, error)
}

func RegisterCommandServer(s *grpc.Server, srv CommandServer) {
	s.RegisterService(&_Command_serviceDesc, srv)
}

func _Command_DoCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CommandServer).DoCommand(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Command_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Command",
	HandlerType: (*CommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoCommand",
			Handler:    _Command_DoCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4d, 0x2f, 0x4a,
	0x4d, 0xcf, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a, 0xe2,
	0xe2, 0x73, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x12, 0xe2, 0x62, 0xc9, 0xcb, 0x4c, 0xce, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x85, 0x24, 0xb8, 0xd8, 0x93, 0x21, 0xaa, 0x24, 0x98, 0xc0, 0xc2, 0x30, 0x2e, 0x48, 0x75, 0x62,
	0x51, 0x7a, 0xb1, 0x04, 0xb3, 0x02, 0x33, 0x48, 0x35, 0x88, 0xad, 0xa4, 0xce, 0xc5, 0x0f, 0x37,
	0xb3, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x84, 0x8b, 0xb5, 0x28, 0xb5, 0x20, 0xa7, 0x12,
	0x68, 0x2a, 0x48, 0x1d, 0x84, 0x63, 0xe4, 0xc8, 0xc5, 0x0e, 0x55, 0x28, 0x64, 0xc6, 0xc5, 0xe9,
	0x92, 0x0f, 0xe3, 0x08, 0xe9, 0x15, 0x24, 0xe9, 0xa1, 0x3a, 0x4b, 0x4a, 0x18, 0x45, 0x0c, 0x62,
	0xac, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x2b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xe1,
	0xa5, 0x17, 0xdb, 0x00, 0x00, 0x00,
}
