// Code generated by protoc-gen-go.
// source: egregor.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	egregor.proto

It has these top-level messages:
	CommandRequest
	CommandResponse
	HelpRequest
	Empty
	CommandList
	CommandEntry
	LogMessage
	LogResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CommandRequest struct {
	Nick    string   `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
	Command string   `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
}

func (m *CommandRequest) Reset()                    { *m = CommandRequest{} }
func (m *CommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()               {}
func (*CommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CommandResponse struct {
	Reply []string `protobuf:"bytes,1,rep,name=reply" json:"reply,omitempty"`
}

func (m *CommandResponse) Reset()                    { *m = CommandResponse{} }
func (m *CommandResponse) String() string            { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()               {}
func (*CommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HelpRequest struct {
	Command string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
}

func (m *HelpRequest) Reset()                    { *m = HelpRequest{} }
func (m *HelpRequest) String() string            { return proto.CompactTextString(m) }
func (*HelpRequest) ProtoMessage()               {}
func (*HelpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CommandList struct {
	List []*CommandEntry `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *CommandList) Reset()                    { *m = CommandList{} }
func (m *CommandList) String() string            { return proto.CompactTextString(m) }
func (*CommandList) ProtoMessage()               {}
func (*CommandList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CommandList) GetList() []*CommandEntry {
	if m != nil {
		return m.List
	}
	return nil
}

type CommandEntry struct {
	Command     string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *CommandEntry) Reset()                    { *m = CommandEntry{} }
func (m *CommandEntry) String() string            { return proto.CompactTextString(m) }
func (*CommandEntry) ProtoMessage()               {}
func (*CommandEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type LogMessage struct {
	Time int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Nick string `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	Body string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *LogMessage) Reset()                    { *m = LogMessage{} }
func (m *LogMessage) String() string            { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()               {}
func (*LogMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type LogResponse struct {
	Reply string `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`
}

func (m *LogResponse) Reset()                    { *m = LogResponse{} }
func (m *LogResponse) String() string            { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()               {}
func (*LogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*CommandRequest)(nil), "pb.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "pb.CommandResponse")
	proto.RegisterType((*HelpRequest)(nil), "pb.HelpRequest")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*CommandList)(nil), "pb.CommandList")
	proto.RegisterType((*CommandEntry)(nil), "pb.CommandEntry")
	proto.RegisterType((*LogMessage)(nil), "pb.LogMessage")
	proto.RegisterType((*LogResponse)(nil), "pb.LogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for Command service

type CommandClient interface {
	DoCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	GetUsage(ctx context.Context, in *HelpRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	GetCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error)
}

type commandClient struct {
	cc *grpc.ClientConn
}

func NewCommandClient(cc *grpc.ClientConn) CommandClient {
	return &commandClient{cc}
}

func (c *commandClient) DoCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := grpc.Invoke(ctx, "/pb.Command/DoCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandClient) GetUsage(ctx context.Context, in *HelpRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := grpc.Invoke(ctx, "/pb.Command/GetUsage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandClient) GetCommands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandList, error) {
	out := new(CommandList)
	err := grpc.Invoke(ctx, "/pb.Command/GetCommands", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Command service

type CommandServer interface {
	DoCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	GetUsage(context.Context, *HelpRequest) (*CommandResponse, error)
	GetCommands(context.Context, *Empty) (*CommandList, error)
}

func RegisterCommandServer(s *grpc.Server, srv CommandServer) {
	s.RegisterService(&_Command_serviceDesc, srv)
}

func _Command_DoCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CommandServer).DoCommand(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Command_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(HelpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CommandServer).GetUsage(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Command_GetCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CommandServer).GetCommands(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Command_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Command",
	HandlerType: (*CommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoCommand",
			Handler:    _Command_DoCommand_Handler,
		},
		{
			MethodName: "GetUsage",
			Handler:    _Command_GetUsage_Handler,
		},
		{
			MethodName: "GetCommands",
			Handler:    _Command_GetCommands_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

// Client API for Log service

type LogClient interface {
	Log(ctx context.Context, opts ...grpc.CallOption) (Log_LogClient, error)
}

type logClient struct {
	cc *grpc.ClientConn
}

func NewLogClient(cc *grpc.ClientConn) LogClient {
	return &logClient{cc}
}

func (c *logClient) Log(ctx context.Context, opts ...grpc.CallOption) (Log_LogClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Log_serviceDesc.Streams[0], c.cc, "/pb.Log/Log", opts...)
	if err != nil {
		return nil, err
	}
	x := &logLogClient{stream}
	return x, nil
}

type Log_LogClient interface {
	Send(*LogResponse) error
	Recv() (*LogMessage, error)
	grpc.ClientStream
}

type logLogClient struct {
	grpc.ClientStream
}

func (x *logLogClient) Send(m *LogResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *logLogClient) Recv() (*LogMessage, error) {
	m := new(LogMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Log service

type LogServer interface {
	Log(Log_LogServer) error
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_Log_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogServer).Log(&logLogServer{stream})
}

type Log_LogServer interface {
	Send(*LogMessage) error
	Recv() (*LogResponse, error)
	grpc.ServerStream
}

type logLogServer struct {
	grpc.ServerStream
}

func (x *logLogServer) Send(m *LogMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *logLogServer) Recv() (*LogResponse, error) {
	m := new(LogResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Log",
	HandlerType: (*LogServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Log",
			Handler:       _Log_Log_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x4e, 0xc2, 0x30,
	0x14, 0xa5, 0x0c, 0x44, 0x6e, 0x15, 0x4c, 0xf5, 0x61, 0xe1, 0x89, 0x54, 0x13, 0x49, 0x34, 0xc4,
	0x8c, 0xc4, 0x1f, 0x50, 0x22, 0x31, 0xf8, 0xb2, 0xc4, 0x0f, 0x60, 0xd0, 0x2c, 0x8b, 0x6c, 0xad,
	0x6d, 0x7d, 0xd8, 0xef, 0xf8, 0xa5, 0xb6, 0x5d, 0x59, 0x4a, 0x22, 0x4f, 0xbb, 0xf7, 0xf4, 0xdc,
	0x73, 0x7b, 0x4e, 0x07, 0x97, 0x2c, 0x97, 0x2c, 0xe7, 0x72, 0x2e, 0x24, 0xd7, 0x9c, 0x74, 0x45,
	0x46, 0x53, 0x18, 0xbd, 0xf0, 0xb2, 0xdc, 0x54, 0xbb, 0x94, 0x7d, 0xff, 0x30, 0xa5, 0x09, 0x81,
	0x5e, 0x55, 0x6c, 0xbf, 0x62, 0x34, 0x45, 0xb3, 0x61, 0xea, 0x6a, 0x12, 0xc3, 0x60, 0xdb, 0xb0,
	0xe2, 0xae, 0x83, 0x0f, 0xad, 0x65, 0x6f, 0x64, 0xae, 0xe2, 0x68, 0x1a, 0x59, 0xb6, 0xad, 0xe9,
	0x3d, 0x8c, 0x5b, 0x4d, 0x25, 0x78, 0xa5, 0x18, 0xb9, 0x81, 0xbe, 0x64, 0x62, 0x5f, 0x1b, 0x55,
	0xcb, 0x6b, 0x1a, 0x43, 0xc4, 0x2b, 0xb6, 0x17, 0x87, 0xcd, 0xc1, 0x16, 0x74, 0xb4, 0x85, 0x0e,
	0xa0, 0xbf, 0x2c, 0x85, 0xae, 0xe9, 0x02, 0xb0, 0x97, 0x5e, 0x17, 0x66, 0xe2, 0x0e, 0x7a, 0x7b,
	0xf3, 0x75, 0xaa, 0x38, 0xb9, 0x9a, 0x8b, 0x6c, 0xee, 0x8f, 0x97, 0x95, 0x96, 0x75, 0xea, 0x4e,
	0xe9, 0x3b, 0x5c, 0x84, 0xe8, 0xe9, 0x3d, 0x64, 0x0a, 0x78, 0xc7, 0xd4, 0x56, 0x16, 0x42, 0x17,
	0xbc, 0xf2, 0x5e, 0x43, 0x88, 0xae, 0x00, 0xd6, 0x3c, 0xff, 0x60, 0x4a, 0x6d, 0x72, 0x66, 0xdd,
	0xeb, 0xa2, 0x64, 0x4e, 0x26, 0x4a, 0x5d, 0xdd, 0xe6, 0xd7, 0x0d, 0xf2, 0x33, 0x58, 0xc6, 0x77,
	0xb5, 0x49, 0xc9, 0x61, 0xb6, 0xa6, 0xb7, 0x80, 0x8d, 0xd2, 0x7f, 0x09, 0xa1, 0x36, 0xa1, 0xe4,
	0x17, 0xc1, 0xc0, 0xdf, 0x9d, 0x3c, 0xc3, 0xf0, 0x95, 0x1f, 0x1a, 0x12, 0x78, 0xf5, 0xf9, 0x4d,
	0xae, 0x8f, 0xb0, 0x46, 0x97, 0x76, 0x48, 0x02, 0xe7, 0x6f, 0x4c, 0x7f, 0xba, 0x0b, 0x8f, 0x2d,
	0x25, 0xc8, 0xfc, 0xd4, 0xcc, 0x03, 0x60, 0x33, 0xe3, 0x71, 0x45, 0x86, 0x96, 0xe5, 0x5e, 0x60,
	0x32, 0x0e, 0x06, 0xec, 0x1b, 0xd0, 0x4e, 0xb2, 0x80, 0xc8, 0x38, 0x21, 0x8f, 0xcd, 0xc7, 0x11,
	0x02, 0x67, 0x93, 0x91, 0x07, 0x7c, 0x68, 0xb4, 0x33, 0x43, 0x4f, 0x28, 0x3b, 0x73, 0xff, 0xe0,
	0xe2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x46, 0x33, 0x04, 0x67, 0x94, 0x02, 0x00, 0x00,
}
